#define NtAcceptConnectPort 0
#define NtAccessCheck 1
#define NtAccessCheckAndAuditAlarm 2
#define NtAccessCheckByType 3
#define NtAccessCheckByTypeAndAuditAlarm 4
#define NtAccessCheckByTypeResultList 5
#define NtAccessCheckByTypeResultListAndAuditAlarm 6
#define NtAccessCheckByTypeResultListAndAuditAlarmByHandle 7
#define NtAddAtom 8
#define NtAddBootEntry 9
#define NtAdjustGroupsToken 10
#define NtAdjustPrivilegesToken 11
#define NtAlertResumeThread 12
#define NtAlertThread 13
#define NtAllocateLocallyUniqueId 14
#define NtAllocateUserPhysicalPages 15
#define NtAllocateUuids 16
#define NtAllocateVirtualMemory 17
#define NtAreMappedFilesTheSame 18
#define NtAssignProcessToJobObject 19
#define NtCallbackReturn 20
#define NtCancelDeviceWakeupRequest 21
#define NtCancelIoFile 22
#define NtCancelTimer 23
#define NtClearEvent 24
#define NtClose 25
#define NtCloseObjectAuditAlarm 26
#define NtCompactKeys 27
#define NtCompareTokens 28
#define NtCompleteConnectPort 29
#define NtCompressKey 30
#define NtConnectPort 31
#define NtContinue 32
#define NtCreateDebugObject 33
#define NtCreateDirectoryObject 34
#define NtCreateEvent 35
#define NtCreateEventPair 36
#define NtCreateFile 37
#define NtCreateIoCompletion 38
#define NtCreateJobObject 39
#define NtCreateJobSet 40
#define NtCreateKey 41
#define NtCreateMailslotFile 42
#define NtCreateMutant 43
#define NtCreateNamedPipeFile 44
#define NtCreatePagingFile 45
#define NtCreatePort 46
#define NtCreateProcess 47
#define NtCreateProcessEx 48
#define NtCreateProfile 49
#define NtCreateSection 50
#define NtCreateSemaphore 51
#define NtCreateSymbolicLinkObject 52
#define NtCreateThread 53
#define NtCreateTimer 54
#define NtCreateToken 55
#define NtCreateWaitablePort 56
#define NtDebugActiveProcess 57
#define NtDebugContinue 58
#define NtDelayExecution 59
#define NtDeleteAtom 60
#define NtDeleteBootEntry 61
#define NtDeleteFile 62
#define NtDeleteKey 63
#define NtDeleteObjectAuditAlarm 64
#define NtDeleteValueKey 65
#define NtDeviceIoControlFile 66
#define NtDisplayString 67
#define NtDuplicateObject 68
#define NtDuplicateToken 69
#define NtEnumerateBootEntries 70
#define NtEnumerateKey 71
#define NtEnumerateSystemEnvironmentValuesEx 72
#define NtEnumerateValueKey 73
#define NtExtendSection 74
#define NtFilterToken 75
#define NtFindAtom 76
#define NtFlushBuffersFile 77
#define NtFlushInstructionCache 78
#define NtFlushKey 79
#define NtFlushVirtualMemory 80
#define NtFlushWriteBuffer 81
#define NtFreeUserPhysicalPages 82
#define NtFreeVirtualMemory 83
#define NtFsControlFile 84
#define NtGetContextThread 85
#define NtGetDevicePowerState 86
#define NtGetPlugPlayEvent 87
#define NtGetWriteWatch 88
#define NtImpersonateAnonymousToken 89
#define NtImpersonateClientOfPort 90
#define NtImpersonateThread 91
#define NtInitializeRegistry 92
#define NtInitiatePowerAction 93
#define NtIsProcessInJob 94
#define NtIsSystemResumeAutomatic 95
#define NtListenPort 96
#define NtLoadDriver 97
#define NtLoadKey 98
#define NtLoadKey2 99
#define NtLockFile 100
#define NtLockProductActivationKeys 101
#define NtLockRegistryKey 102
#define NtLockVirtualMemory 103
#define NtMakePermanentObject 104
#define NtMakeTemporaryObject 105
#define NtMapUserPhysicalPages 106
#define NtMapUserPhysicalPagesScatter 107
#define NtMapViewOfSection 108
#define NtModifyBootEntry 109
#define NtNotifyChangeDirectoryFile 110
#define NtNotifyChangeKey 111
#define NtNotifyChangeMultipleKeys 112
#define NtOpenDirectoryObject 113
#define NtOpenEvent 114
#define NtOpenEventPair 115
#define NtOpenFile 116
#define NtOpenIoCompletion 117
#define NtOpenJobObject 118
#define NtOpenKey 119
#define NtOpenMutant 120
#define NtOpenObjectAuditAlarm 121
#define NtOpenProcess 122
#define NtOpenProcessToken 123
#define NtOpenProcessTokenEx 124
#define NtOpenSection 125
#define NtOpenSemaphore 126
#define NtOpenSymbolicLinkObject 127
#define NtOpenThread 128
#define NtOpenThreadToken 129
#define NtOpenThreadTokenEx 130
#define NtOpenTimer 131
#define NtPlugPlayControl 132
#define NtPowerInformation 133
#define NtPrivilegeCheck 134
#define NtPrivilegeObjectAuditAlarm 135
#define NtPrivilegedServiceAuditAlarm 136
#define NtProtectVirtualMemory 137
#define NtPulseEvent 138
#define NtQueryAttributesFile 139
#define NtQueryBootEntryOrder 140
#define NtQueryBootOptions 141
#define NtQueryDebugFilterState 142
#define NtQueryDefaultLocale 143
#define NtQueryDefaultUILanguage 144
#define NtQueryDirectoryFile 145
#define NtQueryDirectoryObject 146
#define NtQueryEaFile 147
#define NtQueryEvent 148
#define NtQueryFullAttributesFile 149
#define NtQueryInformationAtom 150
#define NtQueryInformationFile 151
#define NtQueryInformationJobObject 152
#define NtQueryInformationPort 153
#define NtQueryInformationProcess 154
#define NtQueryInformationThread 155
#define NtQueryInformationToken 156
#define NtQueryInstallUILanguage 157
#define NtQueryIntervalProfile 158
#define NtQueryIoCompletion 159
#define NtQueryKey 160
#define NtQueryMultipleValueKey 161
#define NtQueryMutant 162
#define NtQueryObject 163
#define NtQueryOpenSubKeys 164
#define NtQueryPerformanceCounter 165
#define NtQueryQuotaInformationFile 166
#define NtQuerySection 167
#define NtQuerySecurityObject 168
#define NtQuerySemaphore 169
#define NtQuerySymbolicLinkObject 170
#define NtQuerySystemEnvironmentValue 171
#define NtQuerySystemEnvironmentValueEx 172
#define NtQuerySystemInformation 173
#define NtQuerySystemTime 174
#define NtQueryTimer 175
#define NtQueryTimerResolution 176
#define NtQueryValueKey 177
#define NtQueryVirtualMemory 178
#define NtQueryVolumeInformationFile 179
#define NtQueueApcThread 180
#define NtRaiseException 181
#define NtRaiseHardError 182
#define NtReadFile 183
#define NtReadFileScatter 184
#define NtReadRequestData 185
#define NtReadVirtualMemory 186
#define NtRegisterThreadTerminatePort 187
#define NtReleaseMutant 188
#define NtReleaseSemaphore 189
#define NtRemoveIoCompletion 190
#define NtRemoveProcessDebug 191
#define NtRenameKey 192
#define NtReplaceKey 193
#define NtReplyPort 194
#define NtReplyWaitReceivePort 195
#define NtReplyWaitReceivePortEx 196
#define NtReplyWaitReplyPort 197
#define NtRequestDeviceWakeup 198
#define NtRequestPort 199
#define NtRequestWaitReplyPort 200
#define NtRequestWakeupLatency 201
#define NtResetEvent 202
#define NtResetWriteWatch 203
#define NtRestoreKey 204
#define NtResumeProcess 205
#define NtResumeThread 206
#define NtSaveKey 207
#define NtSaveKeyEx 208
#define NtSaveMergedKeys 209
#define NtSecureConnectPort 210
#define NtSetBootEntryOrder 211
#define NtSetBootOptions 212
#define NtSetContextThread 213
#define NtSetDebugFilterState 214
#define NtSetDefaultHardErrorPort 215
#define NtSetDefaultLocale 216
#define NtSetDefaultUILanguage 217
#define NtSetEaFile 218
#define NtSetEvent 219
#define NtSetEventBoostPriority 220
#define NtSetHighEventPair 221
#define NtSetHighWaitLowEventPair 222
#define NtSetInformationDebugObject 223
#define NtSetInformationFile 224
#define NtSetInformationJobObject 225
#define NtSetInformationKey 226
#define NtSetInformationObject 227
#define NtSetInformationProcess 228
#define NtSetInformationThread 229
#define NtSetInformationToken 230
#define NtSetIntervalProfile 231
#define NtSetIoCompletion 232
#define NtSetLdtEntries 233
#define NtSetLowEventPair 234
#define NtSetLowWaitHighEventPair 235
#define NtSetQuotaInformationFile 236
#define NtSetSecurityObject 237
#define NtSetSystemEnvironmentValue 238
#define NtSetSystemEnvironmentValueEx 239
#define NtSetSystemInformation 240
#define NtSetSystemPowerState 241
#define NtSetSystemTime 242
#define NtSetThreadExecutionState 243
#define NtSetTimer 244
#define NtSetTimerResolution 245
#define NtSetUuidSeed 246
#define NtSetValueKey 247
#define NtSetVolumeInformationFile 248
#define NtShutdownSystem 249
#define NtSignalAndWaitForSingleObject 250
#define NtStartProfile 251
#define NtStopProfile 252
#define NtSuspendProcess 253
#define NtSuspendThread 254
#define NtSystemDebugControl 255
#define NtTerminateJobObject 256
#define NtTerminateProcess 257
#define NtTerminateThread 258
#define NtTestAlert 259
#define NtTraceEvent 260
#define NtTranslateFilePath 261
#define NtUnloadDriver 262
#define NtUnloadKey 263
#define NtUnloadKeyEx 264
#define NtUnlockFile 265
#define NtUnlockVirtualMemory 266
#define NtUnmapViewOfSection 267
#define NtVdmControl 268
#define NtWaitForDebugEvent 269
#define NtWaitForMultipleObjects 270
#define NtWaitForSingleObject 271
#define NtWaitHighEventPair 272
#define NtWaitLowEventPair 273
#define NtWriteFile 274
#define NtWriteFileGather 275
#define NtWriteRequestData 276
#define NtWriteVirtualMemory 277
#define NtYieldExecution 278
#define NtCreateKeyedEvent 279
#define NtOpenKeyedEvent 280
#define NtReleaseKeyedEvent 281
#define NtWaitForKeyedEvent 282
#define NtQueryPortInformationProcess 283
